#!/bin/bash
rm -r water* 
clear
find source/*.cpp source/*.h -type f -print0 | xargs -0 sed -i "" -E "s/[[:space:]]*$//"
g++ -g -Wall -std=c++11 source/*.cpp -o water

if [ $? ]; then
	if [ "$1" == "debug" ]; then
		gdb water --command=gdb_config
	else
		./water tests/test.h2o 
	fi
fi
