#!/bin/bash
rm -r water* 
clear
find source/*.cpp source/*.h -type f -print0 | xargs -0 sed -i "" -E "s/[[:space:]]*$//"
rm Makefile

cmake CMakeLists.txt
make install
make

if [ -n "$*" ]
then
	./water "$@"
fi
