#!/bin/bash
for file in tests/*.h2o
do
	./water $file > temp.txt
	sed -ie 's/\r/\n/' temp.txt "$file".expected
	diff --brief --ignore-all-space temp.txt "$file".expected
done

rm temp.txt

# TODO: test -r
